### ISSUE TITLE
Add comment with summary of work 

### ISSUE THREAD

**Issue by visibilityspots** [Inuits/12to8#46]
I could be overlooking it, but currently I miss a feature where one could specify a message with a summary of his done work for the created performance.

**Comment by visibilityspots** [comment]
Yep I overlooked it:

Usage:
  12to8 new performance -p options dd[/MM[/YYYY]] H [DESCRIPTION] [flags]

**Comment by roidelapluie** [comment]
Yes, just it is not mandatory
